In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn

In [14]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans

vectorizer = TfidfVectorizer()

df = pd.read_csv('../data/quran.csv')
cols = list(df.columns)
cols[0] = 'chapter#' 
cols[1] = 'verse#'
cols[2] = 'd_verse'
cols[3] = 'verse'
cols[9] = 'd_chapter'
cols[10] = 'chapter'
df.columns = cols

df = df.sort_values(by=['chapter#','verse#']).reset_index(drop=True)
df.drop([6459], axis=0, inplace=True)

In [15]:
for idx, x in df['verse'].items():
    if pd.isna(x): print(idx)

In [16]:
df[pd.isna(df.verse)]
df.tail()

,chapter#,verse#,d_verse,verse,22b81fd12c136d4cf67a37de941908d83eaf8e97571c4983f9308d30d52ad8f9,0.25,1.1,١,1.2,d_chapter,chapter,1.3,0.1
6454,114,2,مَلِكِ ٱلنَّاسِ,ملك الناس,ee43221a2d70da314a28481e2858b355b84ea76cc5505a...,60.0,604,٦٠٤,6456,سُورَةُ النَّاسِ,سورة الناس,30,0
6455,114,3,إِلَٰهِ ٱلنَّاسِ,الٰه الناس,83ea524a3332531b96d8b06c387410ac2371c0e79d7960...,60.0,604,٦٠٤,6457,سُورَةُ النَّاسِ,سورة الناس,30,0
6456,114,4,مِن شَرِّ ٱلۡوَسۡوَاسِ ٱلۡخَنَّاسِ,من شر الوسواس الخناس,04af28c8924483450a6968f46189467994eccf451daa8a...,60.0,604,٦٠٤,6458,سُورَةُ النَّاسِ,سورة الناس,30,0
6457,114,5,ٱلَّذِي يُوَسۡوِسُ فِي صُدُورِ ٱلنَّاسِ,الذي يوسوس في صدور الناس,6d5da11704c8c0a3fce24b7038f963c0ff6922063d7673...,60.0,604,٦٠٤,6459,سُورَةُ النَّاسِ,سورة الناس,30,0
6458,114,6,مِنَ ٱلۡجِنَّةِ وَٱلنَّاسِ,من الجنة والناس,3020b3a83101b27789ad8db9a84b00a9c97271013bf79e...,60.0,604,٦٠٤,6460,سُورَةُ النَّاسِ,سورة الناس,30,0

In [18]:
x = vectorizer.fit_transform(df['verse'])

kmeans = KMeans(n_clusters=30, random_state=42)
df['cluster'] = kmeans.fit_predict(x)
print(df)

      chapter#  verse#                                   d_verse  \
0            1       1    بِسۡمِ ٱللَّهِ ٱلرَّحۡمَٰنِ ٱلرَّحِيمِ
1            1       2     ٱلۡحَمۡدُ لِلَّهِ رَبِّ ٱلۡعَٰلَمِينَ
2            1       3                   ٱلرَّحۡمَٰنِ ٱلرَّحِيمِ
3            1       4                   مَٰلِكِ يَوۡمِ ٱلدِّينِ
4            1       5  إِيَّاكَ نَعۡبُدُ وَإِيَّاكَ نَسۡتَعِينُ
...        ...     ...                                       ...
6454       114       2                           مَلِكِ ٱلنَّاسِ
6455       114       3                          إِلَٰهِ ٱلنَّاسِ
6456       114       4        مِن شَرِّ ٱلۡوَسۡوَاسِ ٱلۡخَنَّاسِ
6457       114       5   ٱلَّذِي يُوَسۡوِسُ فِي صُدُورِ ٱلنَّاسِ
6458       114       6                مِنَ ٱلۡجِنَّةِ وَٱلنَّاسِ

                         verse  \
0      بسم الله الرحمٰن الرحيم
1        الحمد لله رب العٰلمين
2               الرحمٰن الرحيم
3               مٰلك يوم الدين
4       اياك نعبد واياك نستعين
...                        ...
6454                 ملك الناس
6455                الٰه الناس
6456      من شر الوسواس الخناس
6457  الذي يوسوس في صدور الناس
6458           من الجنة والناس

     22b81fd12c136d4cf67a37de941908d83eaf8e97571c4983f9308d30d52ad8f9   0.25  \
0     803dee27b5a9ddf866112eac2f8a34e5bd83ca08015ec4...                 0.25
1     ef2e84a7a99f9340845888a735cf6950853f9e1a13cff3...                 0.25
2     fa43107ca02d890e5115053aed9835bfbefb79ffa68464...                 0.25
3     4355fb3e57b0b8b4e47545d28d30b98359fea1a18e5bfc...                 0.25
4     8fc4ad4ff4e86be9abf8b5c66fd47a316b760844456c87...                 0.25
...                                                 ...                  ...
6454  ee43221a2d70da314a28481e2858b355b84ea76cc5505a...                60.00
6455  83ea524a3332531b96d8b06c387410ac2371c0e79d7960...                60.00
6456  04af28c8924483450a6968f46189467994eccf451daa8a...                60.00
6457  6d5da11704c8c0a3fce24b7038f963c0ff6922063d7673...                60.00
6458  3020b3a83101b27789ad8db9a84b00a9c97271013bf79e...                60.00

      1.1    ١   1.2            d_chapter       chapter  1.3  0.1  cluster
0       1    ١     2  سُورَةُ الفَاتِحَةِ  سورة الفاتحة    1    0       15
1       1    ١     3  سُورَةُ الفَاتِحَةِ  سورة الفاتحة    1    0        4
2       1    ١     4  سُورَةُ الفَاتِحَةِ  سورة الفاتحة    1    0       15
3       1    ١     5  سُورَةُ الفَاتِحَةِ  سورة الفاتحة    1    0        0
4       1    ١     6  سُورَةُ الفَاتِحَةِ  سورة الفاتحة    1    0        0
...   ...  ...   ...                  ...           ...  ...  ...      ...
6454  604  ٦٠٤  6456     سُورَةُ النَّاسِ    سورة الناس   30    0        0
6455  604  ٦٠٤  6457     سُورَةُ النَّاسِ    سورة الناس   30    0       22
6456  604  ٦٠٤  6458     سُورَةُ النَّاسِ    سورة الناس   30    0       14
6457  604  ٦٠٤  6459     سُورَةُ النَّاسِ    سورة الناس   30    0       19
6458  604  ٦٠٤  6460     سُورَةُ النَّاسِ    سورة الناس   30    0       14

[6459 rows x 14 columns]

In [20]:
pd.set_option('display.max_rows', None)  # Show all rows
pd.set_option('display.max_columns', None)  # Show all columns
pd.set_option('display.width', None)  # Don't wrap to fit width
pd.set_option('display.max_colwidth', None)  # Show full column content

df.head(100)

,chapter#,verse#,d_verse,verse,22b81fd12c136d4cf67a37de941908d83eaf8e97571c4983f9308d30d52ad8f9,0.25,1.1,١,1.2,d_chapter,chapter,1.3,0.1,cluster
0,1,1,بِسۡمِ ٱللَّهِ ٱلرَّحۡمَٰنِ ٱلرَّحِيمِ,بسم الله الرحمٰن الرحيم,803dee27b5a9ddf866112eac2f8a34e5bd83ca08015ec4acaaffeba25a378352,0.25,1,١,2,سُورَةُ الفَاتِحَةِ,سورة الفاتحة,1,0,15
1,1,2,ٱلۡحَمۡدُ لِلَّهِ رَبِّ ٱلۡعَٰلَمِينَ,الحمد لله رب العٰلمين,ef2e84a7a99f9340845888a735cf6950853f9e1a13cff30f4c1e7648e56ee51b,0.25,1,١,3,سُورَةُ الفَاتِحَةِ,سورة الفاتحة,1,0,4
2,1,3,ٱلرَّحۡمَٰنِ ٱلرَّحِيمِ,الرحمٰن الرحيم,fa43107ca02d890e5115053aed9835bfbefb79ffa6846491cf7dfc67c8fd8be7,0.25,1,١,4,سُورَةُ الفَاتِحَةِ,سورة الفاتحة,1,0,15
3,1,4,مَٰلِكِ يَوۡمِ ٱلدِّينِ,مٰلك يوم الدين,4355fb3e57b0b8b4e47545d28d30b98359fea1a18e5bfc3dc948eeab653901e5,0.25,1,١,5,سُورَةُ الفَاتِحَةِ,سورة الفاتحة,1,0,0
4,1,5,إِيَّاكَ نَعۡبُدُ وَإِيَّاكَ نَسۡتَعِينُ,اياك نعبد واياك نستعين,8fc4ad4ff4e86be9abf8b5c66fd47a316b760844456c87ec85806ac3473471e9,0.25,1,١,6,سُورَةُ الفَاتِحَةِ,سورة الفاتحة,1,0,0
5,1,6,ٱهۡدِنَا ٱلصِّرَٰطَ ٱلۡمُسۡتَقِيمَ,اهدنا الصرٰط المستقيم,3588b00e5f634a98aad43530808b52caa9b481dad46ddaad45eac81e32ea93c4,0.25,1,١,7,سُورَةُ الفَاتِحَةِ,سورة الفاتحة,1,0,0
6,1,7,صِرَٰطَ ٱلَّذِينَ أَنۡعَمۡتَ عَلَيۡهِمۡ غَيۡرِ ٱلۡمَغۡضُوبِ عَلَيۡهِمۡ وَلَا ٱلضَّآلِّينَ,صرٰط الذين انعمت عليهم غير المغضوب عليهم ولا الضالين,2a2c9b6be73c32c7956511168c280f11d1d7c45d8775749a630dd7ecf09213b4,0.25,1,١,8,سُورَةُ الفَاتِحَةِ,سورة الفاتحة,1,0,5
7,2,0,سُورَةُ البَقَرَةِ,سورة البقرة,b9646eafdec422426ae5fbe958306ee6b0a4471328a4f6289e8599484fed4b70,0.25,2,٢,9,سُورَةُ البَقَرَةِ,سورة البقرة,1,0,6
8,2,0,بِسۡمِ ٱللَّهِ ٱلرَّحۡمَٰنِ ٱلرَّحِيمِ,بسم الله الرحمٰن الرحيم,803dee27b5a9ddf866112eac2f8a34e5bd83ca08015ec4acaaffeba25a378352,0.25,2,٢,10,سُورَةُ البَقَرَةِ,سورة البقرة,1,0,15
9,2,1,الٓمٓ,الم,49c5355bd921dc0d810e3be457432004847a72d5dbe754562be895be707be6c3,0.25,2,٢,11,سُورَةُ البَقَرَةِ,سورة البقرة,1,0,0
10,2,2,ذَٰلِكَ ٱلۡكِتَٰبُ لَا رَيۡبَۛ فِيهِۛ هُدٗى لِّلۡمُتَّقِينَ,ذٰلك الكتٰب لا ريب فيه هدى للمتقين,2dcdd1bdd730654d91f0f03ee211ad5d1f4c908eae548e8f11b0a38cf92cfd14,0.25,2,٢,12,سُورَةُ البَقَرَةِ,سورة البقرة,1,0,0
11,2,3,ٱلَّذِينَ يُؤۡمِنُونَ بِٱلۡغَيۡبِ وَيُقِيمُونَ ٱلصَّلَوٰةَ وَمِمَّا رَزَقۡنَٰهُمۡ يُنفِقُونَ,الذين يؤمنون بالغيب ويقيمون الصلوٰة ومما رزقنٰهم ينفقون,79b5c57358d206f971e88792aea629d7aad0e4a6682340390c833dd675e8b188,0.25,2,٢,13,سُورَةُ البَقَرَةِ,سورة البقرة,1,0,17
12,2,4,وَٱلَّذِينَ يُؤۡمِنُونَ بِمَآ أُنزِلَ إِلَيۡكَ وَمَآ أُنزِلَ مِن قَبۡلِكَ وَبِٱلۡأٓخِرَةِ هُمۡ يُوقِنُونَ,والذين يؤمنون بما انزل اليك وما انزل من قبلك وبالاخرة هم يوقنون,8a133dda67cd25787ca384d36cb7af5b039e42f97c6d083a2f2fb17f12309491,0.25,2,٢,14,سُورَةُ البَقَرَةِ,سورة البقرة,1,0,17
13,2,5,أُوْلَٰٓئِكَ عَلَىٰ هُدٗى مِّن رَّبِّهِمۡۖ وَأُوْلَٰٓئِكَ هُمُ ٱلۡمُفۡلِحُونَ,اولٰئك علىٰ هدى من ربهم واولٰئك هم المفلحون,381af2070a90ebae33240dab0aa8f7081bf05198324d6329e86718e841e29eb5,0.25,2,٢,15,سُورَةُ البَقَرَةِ,سورة البقرة,1,0,1
14,2,6,إِنَّ ٱلَّذِينَ كَفَرُواْ سَوَآءٌ عَلَيۡهِمۡ ءَأَنذَرۡتَهُمۡ أَمۡ لَمۡ تُنذِرۡهُمۡ لَا يُؤۡمِنُونَ,ان الذين كفروا سواء عليهم ءانذرتهم ام لم تنذرهم لا يؤمنون,0fdebd20ed69ff5c47b4a7c951e234950cc7fe170477394e919d44b1defb718a,0.25,3,٣,16,سُورَةُ البَقَرَةِ,سورة البقرة,1,0,12
15,2,7,خَتَمَ ٱللَّهُ عَلَىٰ قُلُوبِهِمۡ وَعَلَىٰ سَمۡعِهِمۡۖ وَعَلَىٰٓ أَبۡصَٰرِهِمۡ غِشَٰوَةٞۖ وَلَهُمۡ عَذَابٌ عَظِيمٞ,ختم الله علىٰ قلوبهم وعلىٰ سمعهم وعلىٰ ابصٰرهم غشٰوة ولهم عذاب عظيم,a0d3c332dce698490d0cec1ef5d737f2fe3670a1a19a4548011e49b532905d80,0.25,3,٣,17,سُورَةُ البَقَرَةِ,سورة البقرة,1,0,26
16,2,8,وَمِنَ ٱلنَّاسِ مَن يَقُولُ ءَامَنَّا بِٱللَّهِ وَبِٱلۡيَوۡمِ ٱلۡأٓخِرِ وَمَا هُم بِمُؤۡمِنِينَ,ومن الناس من يقول ءامنا بالله وباليوم الاخر وما هم بمؤمنين,e04aa01f275a1881b0428f6bff8493a790a1c7758c6ae9fb4bee3db3bb0e7ec0,0.25,3,٣,18,سُورَةُ البَقَرَةِ,سورة البقرة,1,0,17
17,2,9,يُخَٰدِعُونَ ٱللَّهَ وَٱلَّذِينَ ءَامَنُواْ وَمَا يَخۡدَعُونَ إِلَّآ أَنفُسَهُمۡ وَمَا يَشۡعُرُونَ,يخٰدعون الله والذين ءامنوا وما يخدعون الا انفسهم وما يشعرون,db2723cc9eb6e4e18f31d08f7d62e4bd9f396343016b3a3339586a117eb82329,0.25,3,٣,19,سُورَةُ البَقَرَةِ,سورة البقرة,1,0,29
18,2,10,فِي قُلُوبِهِم مَّرَضٞ فَزَادَهُمُ ٱللَّهُ مَرَضٗاۖ وَلَهُمۡ عَذَابٌ أَلِيمُۢ بِمَا كَانُواْ يَكۡذِبُونَ,في قلوبهم مرض فزادهم الله مرضا ولهم عذاب اليم بما كانوا يكذبون,2e8d6c8679eade8ba5eaf9002996604955a015694cf84b9794c94c883e6eb520,0.25,3,٣,20,سُورَةُ البَقَرَةِ,سورة البقرة,1,0,26
19,2,11,وَإِذَا قِيلَ لَهُمۡ لَا تُفۡسِدُواْ فِي ٱلۡأَرۡضِ قَالُوٓاْ إِنَّمَا نَحۡنُ مُصۡلِحُونَ,واذا قيل لهم لا تفسدوا في الارض قالوا انما نحن مصلحون,9e9781c1ebf3eed9cdb01826c4224c3507de25bd3c98e0e30cf2d54fbacf810c,0.25,3,٣,21,سُورَةُ البَقَرَةِ,سورة البقرة,1,0,13
20,2,12,أَلَآ إِنَّهُمۡ هُمُ ٱلۡمُفۡسِدُونَ وَلَٰكِن لَّا يَشۡعُرُونَ,الا انهم هم المفسدون ولٰكن لا يشعرون,74a6027275301fc7fc998c42c97e60b3a07c1d3fc88a413f8cca4e690cc29042,0.25,3,٣,22,سُورَةُ البَقَرَةِ,سورة البقرة,1,0,17
21,2,13,وَإِذَا قِيلَ لَهُمۡ ءَامِنُواْ كَمَآ ءَامَنَ ٱلنَّاسُ قَالُوٓاْ أَنُؤۡمِنُ كَمَآ ءَامَنَ ٱلسُّفَهَآءُۗ أَلَآ إِنَّهُمۡ هُمُ ٱلسُّفَهَآءُ وَلَٰكِن لَّا يَعۡلَمُونَ,واذا قيل لهم ءامنوا كما ءامن الناس قالوا انؤمن كما ءامن السفهاء الا انهم هم السفهاء ولٰكن لا يعلمون,18ec958b021ef9f742ec2338ac32e7c0f44ea821dc931acf6835e712e70b018c,0.25,3,٣,23,سُورَةُ البَقَرَةِ,سورة البقرة,1,0,17
22,2,14,وَإِذَا لَقُواْ ٱلَّذِينَ ءَامَنُواْ قَالُوٓاْ ءَامَنَّا وَإِذَا خَلَوۡاْ إِلَىٰ شَيَٰطِينِهِمۡ قَالُوٓاْ إِنَّا مَعَكُمۡ إِنَّمَا نَحۡنُ مُسۡتَهۡزِءُونَ,واذا لقوا الذين ءامنوا قالوا ءامنا واذا خلوا الىٰ شيٰطينهم قالوا انا معكم انما نحن مستهزءون,78f261b3aac39ae7044b1cf19faf0d934ee765831391d398fafbe6958b133b12,0.25,3,٣,24,سُورَةُ البَقَرَةِ,سورة البقرة,1,0,20
23,2,15,ٱللَّهُ يَسۡتَهۡزِئُ بِهِمۡ وَيَمُدُّهُمۡ فِي طُغۡيَٰنِهِمۡ يَعۡمَهُونَ,الله يستهزئ بهم ويمدهم في طغيٰنهم يعمهون,1839617e7aa48b6025b6a86898c0a14d080b1003c1c163e77d1fd736398736aa,0.25,3,٣,25,سُورَةُ البَقَرَةِ,سورة البقرة,1,0,19
24,2,16,أُوْلَٰٓئِكَ ٱلَّذِينَ ٱشۡتَرَوُاْ ٱلضَّلَٰلَةَ بِٱلۡهُدَىٰ فَمَا رَبِحَت تِّجَٰرَتُهُمۡ وَمَا كَانُواْ مُهۡتَدِينَ,اولٰئك الذين اشتروا الضلٰلة بالهدىٰ فما ربحت تجٰرتهم وما كانوا مهتدين,b802bebe3990d2a3e4713d6968dc66b01ad242f45f6101bc2815d15f88379f12,0.25,3,٣,26,سُورَةُ البَقَرَةِ,سورة البقرة,1,0,1
25,2,17,مَثَلُهُمۡ كَمَثَلِ ٱلَّذِي ٱسۡتَوۡقَدَ نَارٗا فَلَمَّآ أَضَآءَتۡ مَا حَوۡلَهُۥ ذَهَبَ ٱللَّهُ بِنُورِهِمۡ وَتَرَكَهُمۡ فِي ظُلُمَٰتٖ لَّا يُبۡصِرُونَ,مثلهم كمثل الذي استوقد نارا فلما اضاءت ما حوله ذهب الله بنورهم وتركهم في ظلمٰت لا يبصرون,f536334bdacabcc6b3e8a74b4b08c89f6a5acd05859ce26b40c8f6a7f3d44ff5,0.25,4,٤,27,سُورَةُ البَقَرَةِ,سورة البقرة,1,0,19
26,2,18,صُمُّۢ بُكۡمٌ عُمۡيٞ فَهُمۡ لَا يَرۡجِعُونَ,صم بكم عمي فهم لا يرجعون,7156c287af7204b216604209bd7f889edc541e058791b38accba153b717c16b0,0.25,4,٤,28,سُورَةُ البَقَرَةِ,سورة البقرة,1,0,0
27,2,19,أَوۡ كَصَيِّبٖ مِّنَ ٱلسَّمَآءِ فِيهِ ظُلُمَٰتٞ وَرَعۡدٞ وَبَرۡقٞ يَجۡعَلُونَ أَصَٰبِعَهُمۡ فِيٓ ءَاذَانِهِم مِّنَ ٱلصَّوَٰعِقِ حَذَرَ ٱلۡمَوۡتِۚ وَٱللَّهُ مُحِيطُۢ بِٱلۡكَٰفِرِينَ,او كصيب من السماء فيه ظلمٰت ورعد وبرق يجعلون اصٰبعهم في ءاذانهم من الصوٰعق حذر الموت والله محيط بالكٰفرين,aa8df279c939118cea169fd7f354028f69148be56cd5da7791eec3b1a28d9c0b,0.25,4,٤,29,سُورَةُ البَقَرَةِ,سورة البقرة,1,0,14
28,2,20,يَكَادُ ٱلۡبَرۡقُ يَخۡطَفُ أَبۡصَٰرَهُمۡۖ كُلَّمَآ أَضَآءَ لَهُم مَّشَوۡاْ فِيهِ وَإِذَآ أَظۡلَمَ عَلَيۡهِمۡ قَامُواْۚ وَلَوۡ شَآءَ ٱللَّهُ لَذَهَبَ بِسَمۡعِهِمۡ وَأَبۡصَٰرِهِمۡۚ إِنَّ ٱللَّهَ عَلَىٰ كُلِّ شَيۡءٖ قَدِيرٞ,يكاد البرق يخطف ابصٰرهم كلما اضاء لهم مشوا فيه واذا اظلم عليهم قاموا ولو شاء الله لذهب بسمعهم وابصٰرهم ان الله علىٰ كل شيء قدير,2a8015606bdf0824c1941b557b15911c6a1aebb50d9e012855ae3d62fe56d61e,0.25,4,٤,30,سُورَةُ البَقَرَةِ,سورة البقرة,1,0,14
29,2,21,يَٰٓأَيُّهَا ٱلنَّاسُ ٱعۡبُدُواْ رَبَّكُمُ ٱلَّذِي خَلَقَكُمۡ وَٱلَّذِينَ مِن قَبۡلِكُمۡ لَعَلَّكُمۡ تَتَّقُونَ,يٰايها الناس اعبدوا ربكم الذي خلقكم والذين من قبلكم لعلكم تتقون,46fa7f5542cb2779bc125556e86cbdc9d94b69c0dd682da956b8b5ad8f54b1c2,0.25,4,٤,31,سُورَةُ البَقَرَةِ,سورة البقرة,1,0,14
30,2,22,ٱلَّذِي جَعَلَ لَكُمُ ٱلۡأَرۡضَ فِرَٰشٗا وَٱلسَّمَآءَ بِنَآءٗ وَأَنزَلَ مِنَ ٱلسَّمَآءِ مَآءٗ فَأَخۡرَجَ بِهِۦ مِنَ ٱلثَّمَرَٰتِ رِزۡقٗا لَّكُمۡۖ فَلَا تَجۡعَلُواْ لِلَّهِ أَندَادٗا وَأَنتُمۡ تَعۡلَمُونَ,الذي جعل لكم الارض فرٰشا والسماء بناء وانزل من السماء ماء فاخرج به من الثمرٰت رزقا لكم فلا تجعلوا لله اندادا وانتم تعلمون,08cded3d417e0ce362f5eb4afb8cd9656c1253fb38c1bca78f918d7a91d5149d,0.25,4,٤,32,سُورَةُ البَقَرَةِ,سورة البقرة,1,0,9
31,2,23,وَإِن كُنتُمۡ فِي رَيۡبٖ مِّمَّا نَزَّلۡنَا عَلَىٰ عَبۡدِنَا فَأۡتُواْ بِسُورَةٖ مِّن مِّثۡلِهِۦ وَٱدۡعُواْ شُهَدَآءَكُم مِّن دُونِ ٱللَّهِ إِن كُنتُمۡ صَٰدِقِينَ,وان كنتم في ريب مما نزلنا علىٰ عبدنا فاتوا بسورة من مثله وادعوا شهداءكم من دون الله ان كنتم صٰدقين,4c4cf0bd6eca5e0ab6430e748a57c798110fc89bfe5f0e841128a54ac1a235cf,0.25,4,٤,33,سُورَةُ البَقَرَةِ,سورة البقرة,1,0,25
32,2,24,فَإِن لَّمۡ تَفۡعَلُواْ وَلَن تَفۡعَلُواْ فَٱتَّقُواْ ٱلنَّارَ ٱلَّتِي وَقُودُهَا ٱلنَّاسُ وَٱلۡحِجَارَةُۖ أُعِدَّتۡ لِلۡكَٰفِرِينَ,فان لم تفعلوا ولن تفعلوا فاتقوا النار التي وقودها الناس والحجارة اعدت للكٰفرين,b07041c1aecc03c6da67b4437ce7daa8e1a8fb98bd94885020e2beb5b3eda1f8,0.25,4,٤,34,سُورَةُ البَقَرَةِ,سورة البقرة,1,0,0
33,2,25,وَبَشِّرِ ٱلَّذِينَ ءَامَنُواْ وَعَمِلُواْ ٱلصَّٰلِحَٰتِ أَنَّ لَهُمۡ جَنَّٰتٖ تَجۡرِي مِن تَحۡتِهَا ٱلۡأَنۡهَٰرُۖ كُلَّمَا رُزِقُواْ مِنۡهَا مِن ثَمَرَةٖ رِّزۡقٗا قَالُواْ هَٰذَا ٱلَّذِي رُزِقۡنَا مِن قَبۡلُۖ وَأُتُواْ بِهِۦ مُتَشَٰبِهٗاۖ وَلَهُمۡ فِيهَآ أَزۡوَٰجٞ مُّطَهَّرَةٞۖ وَهُمۡ فِيهَا خَٰلِدُونَ,وبشر الذين ءامنوا وعملوا الصٰلحٰت ان لهم جنٰت تجري من تحتها الانهٰر كلما رزقوا منها من ثمرة رزقا قالوا هٰذا الذي رزقنا من قبل واتوا به متشٰبها ولهم فيها ازوٰج مطهرة وهم فيها خٰلدون,e8dab9dc8b93643d1e7f4e254e893268e2d97f3a874a15c267c8d0802514b4f6,0.25,5,٥,35,سُورَةُ البَقَرَةِ,سورة البقرة,1,0,1
34,2,26,۞إِنَّ ٱللَّهَ لَا يَسۡتَحۡيِۦٓ أَن يَضۡرِبَ مَثَلٗا مَّا بَعُوضَةٗ فَمَا فَوۡقَهَاۚ فَأَمَّا ٱلَّذِينَ ءَامَنُواْ فَيَعۡلَمُونَ أَنَّهُ ٱلۡحَقُّ مِن رَّبِّهِمۡۖ وَأَمَّا ٱلَّذِينَ كَفَرُواْ فَيَقُولُونَ مَاذَآ أَرَادَ ٱللَّهُ بِهَٰذَا مَثَلٗاۘ يُضِلُّ بِهِۦ كَثِيرٗا وَيَهۡدِي بِهِۦ كَثِيرٗاۚ وَمَا يُضِلُّ بِهِۦٓ إِلَّا ٱلۡفَٰسِقِينَ,ان الله لا يستحي ان يضرب مثلا ما بعوضة فما فوقها فاما الذين ءامنوا فيعلمون انه الحق من ربهم واما الذين كفروا فيقولون ماذا اراد الله بهٰذا مثلا يضل به كثيرا ويهدي به كثيرا وما يضل به الا الفٰسقين,3ab93f581d99cd3deb0ad525aef1fec7003a34b39224bdf16e12c88d829319b1,0.50,5,٥,36,سُورَةُ البَقَرَةِ,سورة البقرة,1,0,12
35,2,27,ٱلَّذِينَ يَنقُضُونَ عَهۡدَ ٱللَّهِ مِنۢ بَعۡدِ مِيثَٰقِهِۦ وَيَقۡطَعُونَ مَآ أَمَرَ ٱللَّهُ بِهِۦٓ أَن يُوصَلَ وَيُفۡسِدُونَ فِي ٱلۡأَرۡضِۚ أُوْلَٰٓئِكَ هُمُ ٱلۡخَٰسِرُونَ,الذين ينقضون عهد الله من بعد ميثٰقه ويقطعون ما امر الله به ان يوصل ويفسدون في الارض اولٰئك هم الخٰسرون,b09801480aa18d8e32f581f5f70016352041403f1add44ab4d6ba53ef17ce8bc,0.50,5,٥,37,سُورَةُ البَقَرَةِ,سورة البقرة,1,0,1
36,2,28,كَيۡفَ تَكۡفُرُونَ بِٱللَّهِ وَكُنتُمۡ أَمۡوَٰتٗا فَأَحۡيَٰكُمۡۖ ثُمَّ يُمِيتُكُمۡ ثُمَّ يُحۡيِيكُمۡ ثُمَّ إِلَيۡهِ تُرۡجَعُونَ,كيف تكفرون بالله وكنتم اموٰتا فاحيٰكم ثم يميتكم ثم يحييكم ثم اليه ترجعون,8868b4cd1886468e8097a0aa9d38511839782378431025c2081dbd8fe700f4ba,0.50,5,٥,38,سُورَةُ البَقَرَةِ,سورة البقرة,1,0,2
37,2,29,هُوَ ٱلَّذِي خَلَقَ لَكُم مَّا فِي ٱلۡأَرۡضِ جَمِيعٗا ثُمَّ ٱسۡتَوَىٰٓ إِلَى ٱلسَّمَآءِ فَسَوَّىٰهُنَّ سَبۡعَ سَمَٰوَٰتٖۚ وَهُوَ بِكُلِّ شَيۡءٍ عَلِيمٞ,هو الذي خلق لكم ما في الارض جميعا ثم استوىٰ الى السماء فسوىٰهن سبع سمٰوٰت وهو بكل شيء عليم,1d46cfd791cef8e2baca0703534c88eae12043cf447fcfdc53f92f93ec92a071,0.50,5,٥,39,سُورَةُ البَقَرَةِ,سورة البقرة,1,0,9
38,2,30,وَإِذۡ قَالَ رَبُّكَ لِلۡمَلَٰٓئِكَةِ إِنِّي جَاعِلٞ فِي ٱلۡأَرۡضِ خَلِيفَةٗۖ قَالُوٓاْ أَتَجۡعَلُ فِيهَا مَن يُفۡسِدُ فِيهَا وَيَسۡفِكُ ٱلدِّمَآءَ وَنَحۡنُ نُسَبِّحُ بِحَمۡدِكَ وَنُقَدِّسُ لَكَۖ قَالَ إِنِّيٓ أَعۡلَمُ مَا لَا تَعۡلَمُونَ,واذ قال ربك للملٰئكة اني جاعل في الارض خليفة قالوا اتجعل فيها من يفسد فيها ويسفك الدماء ونحن نسبح بحمدك ونقدس لك قال اني اعلم ما لا تعلمون,bdb6da4868a3e41974f9d4ea0cddf2a205aab5a65b5c87ba130c855d149e0e8f,0.50,6,٦,40,سُورَةُ البَقَرَةِ,سورة البقرة,1,0,19
39,2,31,وَعَلَّمَ ءَادَمَ ٱلۡأَسۡمَآءَ كُلَّهَا ثُمَّ عَرَضَهُمۡ عَلَى ٱلۡمَلَٰٓئِكَةِ فَقَالَ أَنۢبِـُٔونِي بِأَسۡمَآءِ هَٰٓؤُلَآءِ إِن كُنتُمۡ صَٰدِقِينَ,وعلم ءادم الاسماء كلها ثم عرضهم على الملٰئكة فقال انبوني باسماء هٰؤلاء ان كنتم صٰدقين,66ce39b2033fbd0dcadd7df9bd562339c5018cf667cd4a07156ec9ec66a408b3,0.50,6,٦,41,سُورَةُ البَقَرَةِ,سورة البقرة,1,0,25
40,2,32,قَالُواْ سُبۡحَٰنَكَ لَا عِلۡمَ لَنَآ إِلَّا مَا عَلَّمۡتَنَآۖ إِنَّكَ أَنتَ ٱلۡعَلِيمُ ٱلۡحَكِيمُ,قالوا سبحٰنك لا علم لنا الا ما علمتنا انك انت العليم الحكيم,afa435565acb3b0a6ccc54f5a4129c446e1bc4abb78042342c5cf32594a26ea3,0.50,6,٦,42,سُورَةُ البَقَرَةِ,سورة البقرة,1,0,20
41,2,33,قَالَ يَٰٓـَٔادَمُ أَنۢبِئۡهُم بِأَسۡمَآئِهِمۡۖ فَلَمَّآ أَنۢبَأَهُم بِأَسۡمَآئِهِمۡ قَالَ أَلَمۡ أَقُل لَّكُمۡ إِنِّيٓ أَعۡلَمُ غَيۡبَ ٱلسَّمَٰوَٰتِ وَٱلۡأَرۡضِ وَأَعۡلَمُ مَا تُبۡدُونَ وَمَا كُنتُمۡ تَكۡتُمُونَ,قال يٰادم انبئهم باسمائهم فلما انباهم باسمائهم قال الم اقل لكم اني اعلم غيب السمٰوٰت والارض واعلم ما تبدون وما كنتم تكتمون,e18d7084e4f23264481bafedceddf21dc3ad4206714154905fe637abf3e17776,0.50,6,٦,43,سُورَةُ البَقَرَةِ,سورة البقرة,1,0,3
42,2,34,وَإِذۡ قُلۡنَا لِلۡمَلَٰٓئِكَةِ ٱسۡجُدُواْ لِأٓدَمَ فَسَجَدُوٓاْ إِلَّآ إِبۡلِيسَ أَبَىٰ وَٱسۡتَكۡبَرَ وَكَانَ مِنَ ٱلۡكَٰفِرِينَ,واذ قلنا للملٰئكة اسجدوا لادم فسجدوا الا ابليس ابىٰ واستكبر وكان من الكٰفرين,738013afc5980577d2a8c8d80e40080b34b6a4ecf8407313ee6803d6efeb4f8d,0.50,6,٦,44,سُورَةُ البَقَرَةِ,سورة البقرة,1,0,0
43,2,35,وَقُلۡنَا يَٰٓـَٔادَمُ ٱسۡكُنۡ أَنتَ وَزَوۡجُكَ ٱلۡجَنَّةَ وَكُلَا مِنۡهَا رَغَدًا حَيۡثُ شِئۡتُمَا وَلَا تَقۡرَبَا هَٰذِهِ ٱلشَّجَرَةَ فَتَكُونَا مِنَ ٱلظَّٰلِمِينَ,وقلنا يٰادم اسكن انت وزوجك الجنة وكلا منها رغدا حيث شئتما ولا تقربا هٰذه الشجرة فتكونا من الظٰلمين,1ea3c29acaf1fb693f28f529968d053284f8263fe6ba5f2ec5d181fccc2b077c,0.50,6,٦,45,سُورَةُ البَقَرَةِ,سورة البقرة,1,0,0
44,2,36,فَأَزَلَّهُمَا ٱلشَّيۡطَٰنُ عَنۡهَا فَأَخۡرَجَهُمَا مِمَّا كَانَا فِيهِۖ وَقُلۡنَا ٱهۡبِطُواْ بَعۡضُكُمۡ لِبَعۡضٍ عَدُوّٞۖ وَلَكُمۡ فِي ٱلۡأَرۡضِ مُسۡتَقَرّٞ وَمَتَٰعٌ إِلَىٰ حِينٖ,فازلهما الشيطٰن عنها فاخرجهما مما كانا فيه وقلنا اهبطوا بعضكم لبعض عدو ولكم في الارض مستقر ومتٰع الىٰ حين,e0f5a9ca0768ac6525b94a56056026a5966c80835ff2499064a24b73b50c9526,0.50,6,٦,46,سُورَةُ البَقَرَةِ,سورة البقرة,1,0,19
45,2,37,فَتَلَقَّىٰٓ ءَادَمُ مِن رَّبِّهِۦ كَلِمَٰتٖ فَتَابَ عَلَيۡهِۚ إِنَّهُۥ هُوَ ٱلتَّوَّابُ ٱلرَّحِيمُ,فتلقىٰ ءادم من ربه كلمٰت فتاب عليه انه هو التواب الرحيم,d3fb426ea7535eacd01e5f5daf83d9a7ec2ab783e74b42df329279ccc58dc8e1,0.50,6,٦,47,سُورَةُ البَقَرَةِ,سورة البقرة,1,0,28
46,2,38,قُلۡنَا ٱهۡبِطُواْ مِنۡهَا جَمِيعٗاۖ فَإِمَّا يَأۡتِيَنَّكُم مِّنِّي هُدٗى فَمَن تَبِعَ هُدَايَ فَلَا خَوۡفٌ عَلَيۡهِمۡ وَلَا هُمۡ يَحۡزَنُونَ,قلنا اهبطوا منها جميعا فاما ياتينكم مني هدى فمن تبع هداي فلا خوف عليهم ولا هم يحزنون,c5cdadb502c02b9880b503111ce2ff1916434b6f9c550fa7150dc4cd75996972,0.50,7,٧,48,سُورَةُ البَقَرَةِ,سورة البقرة,1,0,17
47,2,39,وَٱلَّذِينَ كَفَرُواْ وَكَذَّبُواْ بِـَٔايَٰتِنَآ أُوْلَٰٓئِكَ أَصۡحَٰبُ ٱلنَّارِۖ هُمۡ فِيهَا خَٰلِدُونَ,والذين كفروا وكذبوا بايٰتنا اولٰئك اصحٰب النار هم فيها خٰلدون,6884ccceff6a47e0e0cb7689e68a1477c4e6088ddfebf607baeb0f7c8a1b35c7,0.50,7,٧,49,سُورَةُ البَقَرَةِ,سورة البقرة,1,0,1
48,2,40,يَٰبَنِيٓ إِسۡرَٰٓءِيلَ ٱذۡكُرُواْ نِعۡمَتِيَ ٱلَّتِيٓ أَنۡعَمۡتُ عَلَيۡكُمۡ وَأَوۡفُواْ بِعَهۡدِيٓ أُوفِ بِعَهۡدِكُمۡ وَإِيَّٰيَ فَٱرۡهَبُونِ,يٰبني اسرٰءيل اذكروا نعمتي التي انعمت عليكم واوفوا بعهدي اوف بعهدكم وايٰي فارهبون,8e1c4ef8ef13f38a20852d2028e83d600d3dd43480c16af2f8c9203d5a551eb3,0.50,7,٧,50,سُورَةُ البَقَرَةِ,سورة البقرة,1,0,0
49,2,41,وَءَامِنُواْ بِمَآ أَنزَلۡتُ مُصَدِّقٗا لِّمَا مَعَكُمۡ وَلَا تَكُونُوٓاْ أَوَّلَ كَافِرِۭ بِهِۦۖ وَلَا تَشۡتَرُواْ بِـَٔايَٰتِي ثَمَنٗا قَلِيلٗا وَإِيَّٰيَ فَٱتَّقُونِ,وءامنوا بما انزلت مصدقا لما معكم ولا تكونوا اول كافر به ولا تشتروا بايٰتي ثمنا قليلا وايٰي فاتقون,c6da96ac6be7fcb0c45600f6c33c116ae77b466853cabab284582c22d86b9d05,0.50,7,٧,51,سُورَةُ البَقَرَةِ,سورة البقرة,1,0,5
50,2,42,وَلَا تَلۡبِسُواْ ٱلۡحَقَّ بِٱلۡبَٰطِلِ وَتَكۡتُمُواْ ٱلۡحَقَّ وَأَنتُمۡ تَعۡلَمُونَ,ولا تلبسوا الحق بالبٰطل وتكتموا الحق وانتم تعلمون,27be33a9eef096f3231d9539aee344993afa4c3cf1f27bf7a6645bfa3b6e9b29,0.50,7,٧,52,سُورَةُ البَقَرَةِ,سورة البقرة,1,0,5
51,2,43,وَأَقِيمُواْ ٱلصَّلَوٰةَ وَءَاتُواْ ٱلزَّكَوٰةَ وَٱرۡكَعُواْ مَعَ ٱلرَّٰكِعِينَ,واقيموا الصلوٰة وءاتوا الزكوٰة واركعوا مع الرٰكعين,32939386c70545d86ea1f8449aba8b9978cd3db74f202ad9ad8c527560731cc9,0.50,7,٧,53,سُورَةُ البَقَرَةِ,سورة البقرة,1,0,0
52,2,44,۞أَتَأۡمُرُونَ ٱلنَّاسَ بِٱلۡبِرِّ وَتَنسَوۡنَ أَنفُسَكُمۡ وَأَنتُمۡ تَتۡلُونَ ٱلۡكِتَٰبَۚ أَفَلَا تَعۡقِلُونَ,اتامرون الناس بالبر وتنسون انفسكم وانتم تتلون الكتٰب افلا تعقلون,8e7aa1e17920f5b840b6f47bb7e471f66a3a0a4ad70f7e8bf2d6433c05de3061,0.75,7,٧,54,سُورَةُ البَقَرَةِ,سورة البقرة,1,0,0
53,2,45,وَٱسۡتَعِينُواْ بِٱلصَّبۡرِ وَٱلصَّلَوٰةِۚ وَإِنَّهَا لَكَبِيرَةٌ إِلَّا عَلَى ٱلۡخَٰشِعِينَ,واستعينوا بالصبر والصلوٰة وانها لكبيرة الا على الخٰشعين,5c61186004487872142e07b96b7eed718faf05bae9145e61ee4f28c3cdafaf41,0.75,7,٧,55,سُورَةُ البَقَرَةِ,سورة البقرة,1,0,0
54,2,46,ٱلَّذِينَ يَظُنُّونَ أَنَّهُم مُّلَٰقُواْ رَبِّهِمۡ وَأَنَّهُمۡ إِلَيۡهِ رَٰجِعُونَ,الذين يظنون انهم ملٰقوا ربهم وانهم اليه رٰجعون,6a58a748685c62695f4669263cd6fe80ea832158c97d5715698dbda9b6f894fa,0.75,7,٧,56,سُورَةُ البَقَرَةِ,سورة البقرة,1,0,0
55,2,47,يَٰبَنِيٓ إِسۡرَٰٓءِيلَ ٱذۡكُرُواْ نِعۡمَتِيَ ٱلَّتِيٓ أَنۡعَمۡتُ عَلَيۡكُمۡ وَأَنِّي فَضَّلۡتُكُمۡ عَلَى ٱلۡعَٰلَمِينَ,يٰبني اسرٰءيل اذكروا نعمتي التي انعمت عليكم واني فضلتكم على العٰلمين,b383c0c39331219757ec21e9019aaad388ebadc1b9d8413fc7da94958c7ebf38,0.75,7,٧,57,سُورَةُ البَقَرَةِ,سورة البقرة,1,0,4
56,2,48,وَٱتَّقُواْ يَوۡمٗا لَّا تَجۡزِي نَفۡسٌ عَن نَّفۡسٖ شَيۡـٔٗا وَلَا يُقۡبَلُ مِنۡهَا شَفَٰعَةٞ وَلَا يُؤۡخَذُ مِنۡهَا عَدۡلٞ وَلَا هُمۡ يُنصَرُونَ,واتقوا يوما لا تجزي نفس عن نفس شيا ولا يقبل منها شفٰعة ولا يؤخذ منها عدل ولا هم ينصرون,a3fa4666acf148f9dd79fcace2b6fe0debb1bbf817c80174875b96a29c2b1f97,0.75,7,٧,58,سُورَةُ البَقَرَةِ,سورة البقرة,1,0,5
57,2,49,وَإِذۡ نَجَّيۡنَٰكُم مِّنۡ ءَالِ فِرۡعَوۡنَ يَسُومُونَكُمۡ سُوٓءَ ٱلۡعَذَابِ يُذَبِّحُونَ أَبۡنَآءَكُمۡ وَيَسۡتَحۡيُونَ نِسَآءَكُمۡۚ وَفِي ذَٰلِكُم بَلَآءٞ مِّن رَّبِّكُمۡ عَظِيمٞ,واذ نجينٰكم من ءال فرعون يسومونكم سوء العذاب يذبحون ابناءكم ويستحيون نساءكم وفي ذٰلكم بلاء من ربكم عظيم,184bd7a01a139b79d047169b34a0796c177a11ca4a14d67ad99a3482dfc69964,0.75,8,٨,59,سُورَةُ البَقَرَةِ,سورة البقرة,1,0,9
58,2,50,وَإِذۡ فَرَقۡنَا بِكُمُ ٱلۡبَحۡرَ فَأَنجَيۡنَٰكُمۡ وَأَغۡرَقۡنَآ ءَالَ فِرۡعَوۡنَ وَأَنتُمۡ تَنظُرُونَ,واذ فرقنا بكم البحر فانجينٰكم واغرقنا ءال فرعون وانتم تنظرون,9ba717aa01e737f1467d40f4d9696151fcc2c120e282589aa1e1bc7b28fa9c55,0.75,8,٨,60,سُورَةُ البَقَرَةِ,سورة البقرة,1,0,0
59,2,51,وَإِذۡ وَٰعَدۡنَا مُوسَىٰٓ أَرۡبَعِينَ لَيۡلَةٗ ثُمَّ ٱتَّخَذۡتُمُ ٱلۡعِجۡلَ مِنۢ بَعۡدِهِۦ وَأَنتُمۡ ظَٰلِمُونَ,واذ وٰعدنا موسىٰ اربعين ليلة ثم اتخذتم العجل من بعده وانتم ظٰلمون,938fee40168bf10261ad4e3946a52e57e4ddfec5538e34cf8d561ecf3eca02bd,0.75,8,٨,61,سُورَةُ البَقَرَةِ,سورة البقرة,1,0,2
60,2,52,ثُمَّ عَفَوۡنَا عَنكُم مِّنۢ بَعۡدِ ذَٰلِكَ لَعَلَّكُمۡ تَشۡكُرُونَ,ثم عفونا عنكم من بعد ذٰلك لعلكم تشكرون,1fb3c0530b618cc7e6b298d28d1d3fba854894b2aae8734b20eb854bec6e4c3c,0.75,8,٨,62,سُورَةُ البَقَرَةِ,سورة البقرة,1,0,2
61,2,53,وَإِذۡ ءَاتَيۡنَا مُوسَى ٱلۡكِتَٰبَ وَٱلۡفُرۡقَانَ لَعَلَّكُمۡ تَهۡتَدُونَ,واذ ءاتينا موسى الكتٰب والفرقان لعلكم تهتدون,36b00b531f8660f69c194154542fb1e19066879e64947a57ebd7cb18b98874aa,0.75,8,٨,63,سُورَةُ البَقَرَةِ,سورة البقرة,1,0,0
62,2,54,وَإِذۡ قَالَ مُوسَىٰ لِقَوۡمِهِۦ يَٰقَوۡمِ إِنَّكُمۡ ظَلَمۡتُمۡ أَنفُسَكُم بِٱتِّخَاذِكُمُ ٱلۡعِجۡلَ فَتُوبُوٓاْ إِلَىٰ بَارِئِكُمۡ فَٱقۡتُلُوٓاْ أَنفُسَكُمۡ ذَٰلِكُمۡ خَيۡرٞ لَّكُمۡ عِندَ بَارِئِكُمۡ فَتَابَ عَلَيۡكُمۡۚ إِنَّهُۥ هُوَ ٱلتَّوَّابُ ٱلرَّحِيمُ,واذ قال موسىٰ لقومه يٰقوم انكم ظلمتم انفسكم باتخاذكم العجل فتوبوا الىٰ بارئكم فاقتلوا انفسكم ذٰلكم خير لكم عند بارئكم فتاب عليكم انه هو التواب الرحيم,5c9087cca95f5002a6981e514c87825dc824cf526f7b0fed036360aec44533e9,0.75,8,٨,64,سُورَةُ البَقَرَةِ,سورة البقرة,1,0,9

In [28]:
mut_dict = {"cluster":[], "verse":[]}
unique_groups = df['cluster'].unique()
for x in unique_groups:
    temp_verse_list = []
    temp_df=df[df.cluster == x]
    for y in temp_df['verse']:
        temp_verse_list.append(y)

    mut_dict['cluster'].append(x)
    mut_dict['verse'].append(temp_verse_list)

mut_df = pd.DataFrame(mut_dict)
mut_df.head(30)

    cluster  \
0        15
1         4
2         0
3         5
4         6
5        17
6         1
7        12
8        26
9        29
10       13
11       20
12       19
13       14
14        9
15       25
16        2
17        3
18       28
19       23
20       10
21        8
22       21
23        7
24       22
25       27
26       18
27       16
28       24
29       11

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    verse